#!/usr/bin/python
# This file is automatically generated by symbiotic-build.sh

versions = {
	'symbiotic' : '4dc6fab5149449caaa52ad9f538fa54388f12ffd',
	'dg' : '52ca3189fa23796bbc097186c0b83924129aad1f',
	'sbt-slicer' : '85c8cb482fecdd065329a55551bae93af2408c7b',
	'sbt-instrumentation' : 'd0251925f23cb0b0faff204ba3f3662b94bef440',
	'klee' : 'a549d22eff3df86710a2b618e8cee889ddc01e6e',
}

llvm_version = '10.0.0'

build_types = {
	'symbiotic' : 'Release',
	'dg' : 'Release',
	'sbt-slicer' : 'Release',
	'sbt-instrumentation' : 'Release',
	'klee' : 'Release',
	'klee-runtime' : 'Release',
}

