# This file is part of CoVeriTeam, a tool for on-demand composition of cooperative verification systems:
# https://gitlab.com/sosy-lab/software/coveriteam
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

path_hostfile:
path_tunefile:
path_mpiexec:

# must be a python executable with mpi4py installed
python_executable:

# default command "%exec -n 1 --mca mca_param_files %path_tunefile --machinefile %path_hostfile %python_exec %script_path"
custom_command: # "%exec -n 1 %python_exec %script_path"